#release configuration
#Thu Jul 04 12:04:54 CEST 2024
completedPhase=check-poms
exec.activateProfiles=github
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.de.starwit\:ai-cockpit.developerConnection=scm\:git\:https\://github.com/starwit/ai-cockpit.git
project.scm.de.starwit\:ai-cockpit.tag=HEAD
project.scm.de.starwit\:application.empty=true
project.scm.de.starwit\:persistence.empty=true
project.scm.de.starwit\:rest.empty=true
project.scm.de.starwit\:service.empty=true
project.scm.de.starwit\:webclient.empty=true
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/starwit/ai-cockpit.git
