replicaCount: 1

image:
  repository: starwitorg/ai-cockpit
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${project.version}

nameOverride: ""
fullnameOverride: "observatory-config"

app:
  context_path: "/ai-cockpit"

service:
  port: 8081

auth:
  enabled: false
  keycloakRealmUrlInternal: http://internal-hostname/realms/aicockpit
  keycloakRealmUrlExternal: https://external-hostname/realms/aicockpit
  clientId: aicockpit
  clientSecret: aicockpit 

postgresql:
  auth:
    database: ai-cockpit
    username: ai-cockpit
    password: ai-cockpit

minio:
  user: minioadmin
  password: minioadmin
  endpoint: http://localhost:9000

# extraEnv: |
#   - name: JAVA_TOOL_OPTIONS
#     value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5000
#   - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
#     value: INFO
#   - name: LOGGING_LEVEL_ROOT
#     value: DEBUG

ingress:
  enabled: true
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: aic.starwit-infra.de
      paths:
        - path: /ai-cockpit
          pathType: ImplementationSpecific
  tls: 
    - secretName: aic.starwit-infra.de
      hosts:
        - aic.starwit-infra.de

resources: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
