
name: Create release

# Full workflow to build and publish Maven, Docker, Helm; TODO automatic version update. Everything depends on version in pom.xml

on:
  workflow_dispatch:
    inputs:
      release-type: # id of input
        description: "prerelease, patch, minor or major"
        required: true
        default: "prerelease"

permissions:
  contents: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ai-cockpit
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg   
  release-type: ${{ github.event.inputs.release-type }}

jobs:
  build:
    name: "Creating maven release"
    runs-on: [self-hosted, linux, X64]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
         maven-version: 3.9.2        
   
    - name: Maven release pepare
      run: mvn -B release:clean release:prepare -Darguments="-DskipTests" --file pom.xml
      env:
         CI: false
 
    - name: Maven release clean
      run: mvn -B release:clean --file pom.xml
      env:
         CI: false

    - name: Get tag name
      run: |
        echo "TAG=$( git describe --abbrev=0 )" >> $GITHUB_ENV

    - name: Maven clean install
      run: mvn clean install --file pom.xml
      env:
         CI: false

    - name: Create github release
      run: gh release create ${{ env.TAG }} -F CHANGELOG.md
      env:
         CI: false
