
name: Create github release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: "Creating maven release"
    runs-on: [self-hosted, linux, X64]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Maven clean install
      run: mvn clean install --file pom.xml
      env:
         CI: false

    - name: create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: CHANGELOG.md