
name: Create release and tag

# Full workflow to build and publish Maven, Docker, Helm; TODO automatic version update. Everything depends on version in pom.xml

on:
  workflow_dispatch:
    inputs:
      release-type: # id of input
        description: "prerelease, patch, minor or major"
        required: true
        default: "prerelease"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ai-cockpit
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg   
  release-type: ${{ github.event.inputs.release-type }}

jobs:
  build:
    name: "Creating changelog and release"
    runs-on: [self-hosted, linux, X64]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
         maven-version: 3.9.2        


    - name: get version from pom.xml
      run: |
        echo "VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )" >> $GITHUB_ENV        
    - name: Build with Maven
      run: mvn -B release:clean release:prepare -Darguments="-DskipTests"
      env:
         CI: false

    - name: get version from pom.xml
      run: |
        echo "VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )" >> $GITHUB_ENV        
    - name: Build with Maven
      run: mvn -B release:clean
      env:
         CI: false