
name: Create release

# Creating maven and github release

on:
  workflow_dispatch:
    inputs:
      release-type: # id of input
        description: "prerelease, patch, minor or major"
        required: true
        default: "prerelease"

permissions:
  contents: write

env:
  release-type: ${{ github.event.inputs.release-type }}
  IMAGE_NAME: ai-cockpit
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg  

jobs:
  build:
    name: "Creating maven and github release"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: Install GH CLI
      uses: dev-hanz-ops/install-gh-cli-action@v0.2.0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
         maven-version: 3.9.2        

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Maven release pepare
      run: | 
        mvn generate-sources --file pom.xml
        git commit -am "modified changelog"
        git push
        mvn -B release:clean release:prepare -Darguments="-DskipTests" --file pom.xml
        mvn -B release:clean --file pom.xml
      env:
         CI: false
 
    - name: Get tag name
      run: |
        echo "TAG=$( git describe --abbrev=0 )" >> $GITHUB_ENV

    - name: Create github release
      run: gh release create ${{ env.TAG }} -F CHANGELOG.md
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ env.DOCKERHUB_ORG }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}