
name: Create release

# Creating maven and github release

on:
  workflow_dispatch:
    inputs:
      release-version: # id of input
        description: "override default release version e.g. with 0.1.0-1"
        required: false

permissions:
  contents: write

env:
  RELEASE_VERSION: ${{ github.event.inputs.release-version }}
  IMAGE_NAME: ai-cockpit
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg  

jobs:
  build:
    name: "Creating maven and github release"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: Install GH CLI
      uses: dev-hanz-ops/install-gh-cli-action@v0.2.0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
         maven-version: 3.9.2      

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20  

    - run: npm --version
    - run: node --version
    - run: mvn --version

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Maven release pepare
      run: | 
        git config --global user.email "code@starwit.de"
        git config --global user.name "Starwit"
        if [! -z ${{ env.RELEASE_VERSION }} ]
          mvn -B build-helper:parse-version versions:set -DnewVersion=${{ env.RELEASE_VERSION }}-SNAPSHOT versions:commit --settings .github/workflows/settings.xml --file pom.xml
        fi
        mvn generate-sources --file pom.xml
        git add .
        if [git status | grep -q modified]
        then
          git commit -m "modified changelog"
          git push
        fi
        mvn -B release:clean release:prepare -Darguments="-DskipTests" --settings .github/workflows/settings.xml --file pom.xml
        mvn -B release:clean --settings .github/workflows/settings.xml --file pom.xml
      env:
         CI: false
         PRIVATE_REPO_USERNAME: ${{ vars.PRIVATE_REPO_USERNAME }}
         MAVEN_REPO_READ: ${{ secrets.MAVEN_REPO_READ }}

 
    - name: Get tag name
      run: |
        echo "TAG=$( git describe --abbrev=0 )" >> $GITHUB_ENV

    - name: Create github release
      run: gh release create ${{ env.TAG }} -F CHANGELOG.md
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout tag
      run: |
        git checkout ${{ env.TAG }}

    - name: npm install
      run: |
        if [ -d "webclient/app" ]; then
          cd webclient/app
          npm install
        fi

    - name: Build with Maven
      run: mvn clean -B package -P frontend --settings .github/workflows/settings.xml --file pom.xml
      env:
         CI: false
         PRIVATE_REPO_USERNAME: ${{ vars.PRIVATE_REPO_USERNAME }}
         MAVEN_REPO_READ: ${{ secrets.MAVEN_REPO_READ }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ env.DOCKERHUB_ORG }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

    - name: get helm
      uses: azure/setup-helm@v3  

    - name: login to Helm registry
      run: helm registry login registry-1.docker.io -u starwit -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: run helm update
      working-directory: application/target/helm/ai-cockpit
      run: helm dep update

    - name: run helm package
      working-directory: application/target/helm
      run: helm package ai-cockpit

    - name: get version number
      working-directory: application/target/helm/ai-cockpit
      run: |
        echo "HELM_VERSION=$(grep version: Chart.yaml | head -1 | awk '{print $2}')" >> $GITHUB_ENV

    - name: run helm push
      working-directory: application/target/helm
      run: helm push ai-cockpit-chart-${{ env.HELM_VERSION }}.tgz oci://registry-1.docker.io/starwitorg