name: PR Build

# PR build

on:
  pull_request:
    branches: [ master, versionupgrade ]
  workflow_dispatch:


# just runs Maven, NPM and Docker build

jobs:
  build:
    name: "PR build"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.2
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --version
    - run: node --version
    - run: mvn --version

    - name: get version from pom.xml
      run: |
        echo "VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )" >> $GITHUB_ENV

    - name: npm install
      run: |
        if [ -d "webclient/app" ]; then
          cd webclient/app
          npm install
        fi        
    - name: Build with Maven
      run: mvn clean -B package -P frontend --file pom.xml
      env:
         CI: false
